### PR TITLE
Clean up the library so that it compiles again

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/fontsan/2)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Add another commit that adds `rust: nightly` to the travis config?

**Comment by nox** [comment]
@frewsxcv Missed that one, I removed it and used std::process::exit() instead, r?

**Comment by frewsxcv** [comment]
The Almighty Travis In The Sky is not pleased

**Comment by frewsxcv** [comment]
You are angering The Almighty Travis In The Sky. Be careful.

**Comment by nox** [comment]
Please accept this offering, Almighty Travis in The Sky.

**Comment by nox** [comment]
The Almighty Travis In The Sky heard my prayers, @frewsxcv.

**Comment by frewsxcv** [comment]
r+

**Comment by nox** [comment]
@frewsxcv You are going to upset The Eternal Homu of the Holy Spirit, by not speaking its name.

**Comment by frewsxcv** [comment]
The Eternal Homu of the Holy Spirit does not acknowledge me as a trusted disciple

**Comment by jdm** [comment]
https://github.com/servo/saltfs/pull/113

**Comment by nox** [comment]
Oh.

**Comment by nox** [comment]
Too soon?

**Pull request merged**
