### PR TITLE
Don’t link with libstdc++ on non-GNU platforms

### PR DESCRIPTION
**Pull request by khaledhosny**
Attempt to fix MSVC build in https://github.com/servo/servo/pull/12938.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/fontsan/16)

### CODE REVIEW

**Comment by nox** [comment]
This is similar to what we do in azure, but in azure we also check that the platform contains windows. Shouldn't it be the same here?

**Comment by nox** [comment]
Thanks for taking a look at that crate btw!

**Comment by khaledhosny** [comment]
We need libstdc++ on any platform where GNU std libs are used e.g. Linux, so checking for Windows first will break them.

**Comment by nox** [comment]
Oh right silly me.

**Comment by nox** [comment]
That would actually break on OS X, which also needs stdc++.

**Comment by nox** [comment]
> 19:35 <vlad> nox: you can just check for !contains("msvc")

**Comment by khaledhosny** [comment]
This builds on Linux and MacOS now.

**Pull request merged**
