### PR TITLE
Build OTS with CMake

### PR DESCRIPTION
**Pull request by khaledhosny**
This is a crude attempt to use CMake to build OTS, which should hopefully help unbreak https://github.com/servo/servo/pull/11649. I appreciate any feedback since I’m neither familiar with rust build system nor CMake.

I also took the opportunity to update OTS to the latest version (which made it easier to just copy the file lists from upstream Makefile.am).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/fontsan/11)

### CODE REVIEW

**Comment by khaledhosny** [comment]
Travis build is failing because of the lack of C++11 support (needed for woff2 module), I’m not sure if it is a limitation of the GCC version on Travis or my CMake skills.

**Comment by khaledhosny** [comment]
I managed to fix the C++11 issue on Travis by using GCC 4.8.

**Comment by metajack** [comment]
examples/check-font.rs has an unused import. Otherwise this is good to go!

r=me

**Comment by khaledhosny** [comment]
That unused import was there from the start AFAICT.

**Comment by metajack** [comment]
We'll fix it in a followup then.

**Pull request merged**
